# Generated by Django 3.0.2 on 2020-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20200123_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
