# Generated by Django 3.0.2 on 2020-01-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_auto_20200123_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='text',
            field=models.TextField(),
        ),
    ]
